### ISSUE TITLE
Consider the addition of enum arguments for some commands

### ISSUE THREAD

**Issue by exodrifter** [exodrifter/unity-rumor#42]
Consider adding enum arguments for some commands, such as:
```
say "This line doesn't require an advance" nowait
pause 0.5
say "And this line appears suddenly!
```
In this example, an enum argument `nowait` is being provided to the `say` command.

If a case can be made for the widespread, useful application of enum arguments, then this feature should be developed and made available. More examples of where this language feature would be useful would help in making this case.

(see: https://twitter.com/SenshiSentou/status/943220264132898816)

**Comment by exodrifter** [comment]
I realized earlier this evening that the `clear` command already uses an `ClearType` enum argument (#21). So, that is at least one place in the repository which already utilizes this language feature.

**Comment by exodrifter** [comment]
After more brainstorming, I have realized another possible enum argument use:
```
pause 0.5 ignore_input
```
I think I have enough examples now of where this kind of language syntax would be useful and it no longer feels applicable only to certain edge cases. I'll be implementing this syntax along with the compiler rehaul I am working on.

**Comment by SenshiSentou** [comment]
Awesome, good point! If I may just nitpick real quick though:

- Since Rumor doesn't deal with input as such, perhaps something like `ignore_advance` or `cant_skip` would be better?
- You've been calling these "enum arguments"; does that mean you're thinking of implementing these as some sort of `ControlOption` enum? If so, it might be worth future-proofing the design by using a `param[]`, just so that a single line can contain multiple options.

Either way, they're really just that, nit picks. Very excited to see this in a future release!

**Comment by exodrifter** [comment]
I agree about `ingore_input` not really making sense for Rumor. I was thinking about doing `ignore_advance`, but it feels too technical for a writer. I think your suggestion of `cant_skip` is a good choice and self-explanatory. I'll update #56 to match.

Your other idea is interesting. The only problem is, most of these enum arguments are specific to the command being used. For example, it doesn't make any sense to do:
```
say "Hello world!" dialog
```
As a result, I don't think this idea would work.

**Comment by SenshiSentou** [comment]
Hmm, very true. My main reasoning was that, if in the future there are multiple options for any given command, it would make sense to easily allow for all possible combinations (`A`, `B`, `A B`, `B A`) that way. I guess it could still make sense if you were to use specific, dedicated enums (`TalkOption{}` for `say` and `add`, `YieldOption{}`, etc.), but I'm probably thinking too much about the implementation here already. ;)
