### ISSUE TITLE
ArgumentOutOfRangeException on example

### ISSUE THREAD

**Issue by dhowe** [exodrifter/unity-rumor#47]
So I made a small modification to the script which causes an error, but I'm not sure why. Waht I was trying for, was for after the choice, in either case, to say "Now for fruit".

Am I missing something about the 'choose' command (maybe an explanatory error message would be helpful here) ?

````
label start:
    say "Hi!"
    say "Is this working?"

    choice "Yes!":
        say "Great!"
    choice "No.":
        say "Darn..."
        pause 0.5
        add "Maybe next time."
    choose
 
    pause 0.5
    say "Now for fruit"


````
ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
System.Collections.Generic.List`1[Exodrifter.Rumor.Lang.LogicalToken].get_Item (Int32 index) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Collections.Generic/List.cs:633)
Exodrifter.Rumor.Lang.RumorCompiler.GetKey (Exodrifter.Rumor.Lang.LogicalLine line, System.Int32& pos, System.Int32& depth) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:174)
Exodrifter.Rumor.Lang.RumorCompiler.GetChildren (System.Collections.Generic.List`1 lines, System.Int32& index, Int32 depth) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:187)
Exodrifter.Rumor.Lang.RumorCompiler.CompileNodes (System.Collections.Generic.List`1 lines, System.Int32& index, Int32 depth) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:236)
Exodrifter.Rumor.Lang.RumorCompiler.GetChildren (System.Collections.Generic.List`1 lines, System.Int32& index, Int32 depth) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:191)
Exodrifter.Rumor.Lang.RumorCompiler.CompileNodes (System.Collections.Generic.List`1 lines, System.Int32& index, Int32 depth) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:236)
Exodrifter.Rumor.Lang.RumorCompiler.Compile (System.String code) (at Assets/Libraries/Rumor/Lang/RumorCompiler.cs:151)
Exodrifter.Rumor.Engine.Rumor..ctor (System.String script) (at Assets/Libraries/Rumor/Engine/Rumor.cs:215)
ScriptedText.Start () (at Assets/Tests/ScriptedTextTest/ScriptedText.cs:14)

**Comment by dhowe** [comment]
(can share my unity project if useful)

**Comment by exodrifter** [comment]
Thank you for the bug report. You're using the commands correctly, but this is an error that I didn't write a proper compiler error message for. The new compiler I'm currently working on is a lot better in this respect.

I was not able to reproduce this error, so if you could provide your Unity project, that would help considerably in fixing this bug.

**Comment by dhowe** [comment]
Not sure why, but I can no longer recreate this error either ...
