### ISSUE TITLE
Using 'say' command with variables

### ISSUE THREAD

**Issue by dhowe** [exodrifter/unity-rumor#54]
I'm prob missing something obvious here, but how do I do:

$ food = "cake"
say me "For lunch I had" + cake

**Comment by exodrifter** [comment]
Your example would work if you used the variable name you assigned the `"cake"` value to.

```
$ me = "me"
$ food = "cake"
say me "For lunch I had " + food
```

**Comment by dhowe** [comment]
sorry, that was a typo... the correctly phrased question is in #53
