### ISSUE TITLE
Tokenizer not handling comma after non-quoted value correctly

### ISSUE THREAD

**Issue by SenshiSentou** [exodrifter/unity-rumor#57]
The line `$do_thing("foo", 1)` gets (correctly) broken up into the following tokens:

    do_thing
    (
    "
    foo
    "
    ,
    
    1
    )

However, when the first argument is an unquoted value (`$do_thing(1, 1)`, `$do_thing(true, 1)`) the comma gets appended to the value token (i.e.: a token of `1,`).

This can be verified by introducing an extra space before-hand: `$do_thing(1 , 1)`. Conversely, calling `$do_thing("foo",1)` without a trailing space results in a `Unexpected tokens after string!` compiler error being thrown, though that might be intentional.

**Comment by exodrifter** [comment]
Thank you for the bug report. It looks like the compiler simply forgot to tell the tokenizer to tokenize commas.

I pushed a commit that should fix this problem. Let me know if it works or if you notice any other related problems.

**Comment by SenshiSentou** [comment]
Derp, such a simple fix. Thanks!
